// Generated by https://quicktype.io
//{"estado_valvulas":[0,0,0,0],"modo_activo":1,"proximo_ciclo":"00:00 Lun","horarios":[1,0,0,11,0,6,9]}
// // Generated by https://quicktype.io

class MqttProtocol {
  List<dynamic> estadoValvulas;
  int modoActivo;
  String proximoCiclo;
  List<dynamic> horarios;
  String hora;
  String fecha;
  

  MqttProtocol({
    this.estadoValvulas,
    this.modoActivo,
    this.proximoCiclo,
    this.horarios,
    this.hora,
    this.fecha,
  });
  MqttProtocol.fromJsonMap(Map<String, dynamic> json) {
    if (json['estado_valvulas'] != null) {
      estadoValvulas = json['estado_valvulas'];
    }
    if (json['modo_activo'] != null) {
      modoActivo = json['modo_activo'];
    }
    if (json['proximo_ciclo'] != null) {
      proximoCiclo = json['proximo_ciclo'];
    }
    if (json['horarios'] != null) {
      horarios = json['horarios'];
    }
    if (json['hora'] != null) {
      hora = json['hora'];
    }
    if (json['fecha'] != null) {
      fecha = json['fecha'];
    }
  }
}
